version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projet_devv
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: projet_devv

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - backend

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  # nexus:
  #   image: sonatype/nexus3
  #   ports:
  #     - "8082:8081"
  #   volumes:
  #     - nexus_data:/nexus-data
  #   # Commentaire : Nexus désactivé pour l'instant.

  # sonarqube:
  #   image: sonarqube:community
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - sonarqube_data:/opt/sonarqube/data
  #     - sonarqube_logs:/opt/sonarqube/logs
  #   # Commentaire : SonarQube désactivé pour l'instant.

volumes:
  mysql_data:
  jenkins_home:
  # nexus_data:
  # sonarqube_data:
  # sonarqube_logs:
